name: Deploy on Docker

on:
  push:
    branches:
      - main

jobs:

  deploy-on-ec2:
    name: Deploy Streamlit
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1

    - name: SSH into EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST_PROD }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
           if [ -d "/home/${{ secrets.EC2_USER }}/auth-movie" ]; then
                cd /home/${{ secrets.EC2_USER }}/auth-movie
                git config pull.rebase false
                git checkout main
                git fetch origin main
                git reset --hard origin/main
           else
                git clone -b main https://${{ secrets.PAT_GITHUB }}@github.com/2003saurabh/auth-movie.git /home/${{ secrets.EC2_USER }}/auth-movie
                cd /home/${{ secrets.EC2_USER }}/auth-movie
                git config --global --add safe.directory $(pwd)
           fi

            cd /home/ec2-user/auth-movie
            docker rm -f auth-movie-container || true
            docker build -t auth-movie .
            docker run --restart always -d -p 8501:8501 --name auth-movie-container auth-movie
